version: '3'

volumes:
  redis:
  postgres:

services:
  db:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0.4-alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data

  api:
    build:
      context: .
      args:
        BUNDLE_WITHOUT: production
    environment:
      RAILS_ENV: development
    env_file: .env
    volumes:
      - .:/app/current
    ports:
      - 3000:3000
      - 1234:1234
    depends_on:
      - redis
      - db
