version: '3'

volumes:
  postgres:

services:
  db:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    build:
      context: .
      args:
        BUNDLE_WITHOUT: production
    environment:
      RAILS_ENV: development
    env_file: .env
    volumes:
      - .:/app/current
    ports:
      - 3000:3000
      - 8080:8080
    depends_on:
      - db
