default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  host: <%= ENV.fetch('DB_HOST') %>

development:
  <<: *default
  database: new_api_development

test:
  <<: *default
  database: new_api_test

production:
  <<: *default
  database: new_api_production
